### ISSUE TITLE
path params를 받는 페이지는 어떻게 지정해야할까요?

### ISSUE THREAD

**Issue by jsb408** [NamGungGeon/react-hydratable#1]
/user/:userId의 경로에서 사용하고 싶은데 (ex. /user/0, /user/1, …)
이 경우에는 config 파일에 어떻게 지정해줘야할까요?

**Comment by NamGungGeon** [comment]
dynamic routing의 경우 모든 가능한 url 조합을 전부 크롤링할 수는 없으므로, 하나하나 지정해주어야 합니다.

`hydratable.config.json`
```json
{
  "crawlingUrls": ["/user/0", "/user/1"]
}
```

**Comment by NamGungGeon** [comment]
대표성을 띄는 몇 가지 url을 선정한 후 크롤링하고 sitemap에 등록하는 것을 권장합니다.
